name: Tests

on: [push, pull_request]

jobs:
  x64-ubuntu:
    name: X64-ubuntu
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.1' # The Go version to download (if necessary) and use.
      - run: date +%F > todays-date
      - name: Restore cache for today's nightly.
        uses: actions/cache@v2
        with:
          path: |
            _neovim
          key: ${{ runner.os }}-x64-${{ hashFiles('todays-date') }}

      - name: Prepare
        run: |
          GO111MODULE=on go get golang.org/x/tools/gopls@latest
          GO111MODULE=on go get mvdan.cc/gofumpt
          go get golang.org/x/tools/cmd/goimports
          go get golang.org/x/tools/cmd/gorename
          go get github.com/fatih/gomodifytags
          go get -u github.com/segmentio/golines
          mkdir -p ~/.local/share/nvim/site/pack/vendor/start
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
          git clone --depth 1 https://github.com/neovim/nvim-lspconfig ~/.local/share/nvim/site/pack/vendor/start/nvim-lspconfig
          git clone --depth 1 https://github.com/nvim-treesitter/nvim-treesitter ~/.local/share/nvim/site/pack/vendor/start/nvim-treesitter
          ln -s $(pwd) ~/.local/share/nvim/site/pack/vendor/start
      - name: Run tests
        run: |
          curl -OL https://raw.githubusercontent.com/norcalli/bot-ci/master/scripts/github-actions-setup.sh
          source github-actions-setup.sh nightly-x64
          nvim --headless -u tests/minimal.vim -c "TSInstallSync all" -c "q"
          make test
